<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="arduinobot">

    <!-- specify some colours -->
    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>
    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

      <!-- Specify some standard inertial calculations -->
   <!-- these make use of xacro's mathematical functionality -->
   
    <xacro:macro name="inertial_box" params="mass x y z *origin">
        <inertial>
          <xacro:insert_block name="origin"/>
          <mass value="${mass}" />
            <inertia ixx = "${(1/12)* mass * (y*y+z*z)}" ixy ="0" ixz ="0"
                 iyy = "${(1/12)* mass * (x*x+z*z)}" iyz ="0" 
                 izz = "${(1/12)* mass * (x*x+y*y)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="inertial_sphere" params="mass radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
                <inertia ixx="${(2/5) * mass * (radius*radius)}" ixy="0.0" ixz="0.0"
                         iyy="${(2/5) * mass * (radius*radius)}" iyz="0.0"
                         izz="${(2/5) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro> 

    <xacro:macro name="inertial_cylinder" params="mass length radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
                <inertia ixx="${(1/12) * mass * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
                         iyy="${(1/12) * mass * (3*radius*radius + length*length)}" iyz="0.0"
                         izz="${(1/2) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>

    <xacro:property name="link_length" value = "0.14" />
    <xacro:property name="link_width" value = "0.05" />
    <xacro:property name="link_height" value = "0.05" />
    <xacro:property name="link_mass" value = "1" />
    <xacro:property name="next_link_with_gap" value = "0.10" />  <!-- next link starting point (0.14/2)+0.03 = 0.1 -->
    <xacro:property name="next_link_cg_with_gap" value = "0.17" /> <!-- next link CG from previous link CG (0.14)+0.03 = 0.17 -->
    

    <!-- Robot is oriented along x-axis --> 
    <!-- <link name="base_link"/> -->
    <link name="world"/>

    <joint name="virtual_joint" type="fixed">
        <parent link="world"/>
        <child link="link_1"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="link_1">
        <visual>
          <origin xyz="${link_length/2} 0 ${link_height/2}" rpy="0 0 0" /> <!-- CG posistion of link_1 --> 
          <geometry>
             <box size="${link_length} ${link_width} ${link_height}"/>
          </geometry>
          <material name="blue"/>
        </visual>
        <collision>
           <origin xyz="${link_length/2} 0 ${link_height/2}" rpy="0 0 0"/>
           <geometry>
             <box size="${link_length} ${link_width} ${link_height}"/>
          </geometry>
        </collision>
        <xacro:inertial_box mass="${link_mass}" x="${link_length}" y="${link_width}" z="${link_height}">
                <origin xyz="${link_length/2} 0 ${link_height/2}" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>


    <!-- <joint name="joint_1" type="revolute">
        <parent link="link_1"/>
        <child link="link_2"/>
        <origin xyz="${link_length} 0.0 0.0" rpy= "0 0 0" />
        <axis xyz = "0 0 1"/>
        <limit lower="${-pi/3}" upper ="${pi/3}" velocity = "100" effort= "100"/>      
    </joint> -->
    <joint name="virtual_joint2" type="fixed">
        <parent link="link_1"/>
        <child link="link_2"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="link_2">
        <visual>
          <origin xyz="${next_link_with_gap} 0 ${link_height/2}" rpy="0 0 0" />
          <geometry>
             <box size="${link_length} ${link_width} ${link_height}"/>
          </geometry>
          <material name="orange"/>
        </visual>
        <collision>
           <origin xyz="${next_link_with_gap} 0 ${link_height/2}" rpy="0 0 0"/>
           <geometry>
             <box size="${link_length} ${link_width} ${link_height}"/>
          </geometry>
        </collision>
        <xacro:inertial_box mass="${link_mass}" x="${link_length}" y="${link_width}" z="${link_height}">
                <origin xyz="${next_link_with_gap} 0 0" rpy="0 0 0" />
        </xacro:inertial_box>
      </link>

</robot>